### PR TITLE
Faster evalcov_blocks

### PR DESCRIPTION
**Pull request by Gattocrucco**
`gvar.evalcov_blocks` is currently the main bottleneck in a code of mine. Of 17 seconds to run the script, 12 are a single call to `evalcov_blocks` from `gvar.raniter`. For comparison, the SVD in `gvar.raniter` then takes only 0.3 seconds. I've determined that the problem is that it is optimized only for the sparse case, so I wrote a version that should handle reasonably well also the dense case.

It is much faster when the the gvars are not primary, because to compute the covariance it uses the same algorithm of `gvar.evalcov`:

```python
import numpy as np
import gvar
from gvar import _evalcov_fast as ef
n = 100
a = np.random.randn(n, n)
cov = a.T @ a
x = gvar.gvar(np.zeros(n), cov)
x = a @ x
%timeit gvar.evalcov_blocks(x)                                                    
%timeit ef.evalcov_blocks(x)
%timeit gvar.evalcov(x)
```

Output: 

```
1.02 s ± 20.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
40.2 ms ± 6.57 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
16.6 ms ± 463 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

So a 25x improvement. For cases were `gvar.evalcov_blocks` was already fine, the performance is comparable:

```python
import numpy as np
import gvar
from gvar import _evalcov_fast as ef
n = 1000
x = gvar.gvar(np.zeros(n), np.arange(n))
%timeit gvar.evalcov_blocks(x, compress=True)                                                    
%timeit ef.evalcov_blocks(x, compress=True)
%timeit gvar.evalcov(x)
```

Output:

```
442 ms ± 11.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
239 ms ± 1.02 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
146 ms ± 2.64 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

By playing with it I've also found cases where it is a bit slower, but there's still optimization to be done in the cython code, so I guess it can be made to be always faster.

Things still to do: the tests are written for pytest, which can run also the rest of the testsuite, but maybe you prefer that I port it to unittest. Other important thing: I've not tried to run all the testsuite, and the lsqfit testsuite, by replacing `evalcov_blocks` with the new one.

### CODE REVIEW

**Comment by Gattocrucco** [comment]
Update: I also successfully ran the gvar and lsqfit testsuites replacing evalcov_blocks.

**Comment by gplepage** [comment]
I was aware of this issue and had made a new version of ``evalcov_blocks`` also using the ``scipy`` ``connected_components.`` My new version was too slow, however. Your pull request caused me to look at it again, and I realized I had accidentally introduced a stupid inefficiency which was greatly slowing it down. I am going to stick with my new version (now fixed), rather than merging your new version, because mine is a lot shorter (around 60 or 70 lines in all) and so will be easier for me to support. My version may not be as fast as yours but it is close. 

I really appreciate your looking at this and demonstrating that it could be improved. It was important and I was stuck. I am impressed with how quickly you built a replacement that worked with the rest of the code.

I will probably post a new version of ``gvar`` sometime tomorrow with this and other improvements. Thanks again.

**Comment by Gattocrucco** [comment]
Wow, how did you made it so short? I had to write a lot of code to avoid bringing in a scipy dependency. Will the next gvar depends explicitly on scipy? I would be happy of that, because the next bottleneck in my code is still gvar code, and I'm thinking about optimizing it, and sometimes scipy has just the right function. Next time though I will first open an issue, so I don't end up doing work you already did.

**Comment by gplepage** [comment]
Yes, I am adding ``scipy`` as a dependency.

**Pull request closed without merging**
